export const SET_CURRENT_SHOP = "NAVIGATION/SET_CURRENT_SHOP";
export const SET_DEFAULT_PAGE_PRODUCT = "NAVIGATION/SET_DEFAULT_PAGE_PRODUCT";
export const SET_PAGE_PRODUCT = "NAVIGATION/SET_PAGE_PRODUCT";
export const SET_COUNT_PRODUCTS_IN_SHOP = "NAVIGATION/SET_COUNT_PRODUCTS_IN_SHOP";

export const ADD_PRODUCT_TO_BASKET = "BASKET/ADD_PRODUCT_TO_BASKET";
export const INIT_DEFAULT_BASKET = "BASKET/INIT_DEFAULT_BASKET";
export const SET_COUNT_PRODUCT_BY_ID = "BASKET/SET_COUNT_PRODUCT_BY_ID";
export const COMPUTE_TOTAL_PRICE = "BASKET/COMPUTE_TOTAL_PRICE";